== Instructions to run temperature controller
Prerequisite
## Install Maven

To install maven, download the binary zip from https://maven.apache.org/download.cgi and follow the install instructions at https://maven.apache.org/install.html.
Linux users: just use your package manager.

## 1. Download the project using below instructions on command line

git clone https://github.com/monikaleoster/kubehello.git

## 2. Change Directory

cd kubehello\complete

## 3. Run the project
mvn spring-boot:run

## 4. Open Swagger-UI on Browser
http://localhost:8080/swagger-ui/#/temperature-controller

## 5. Create Request payload using documentation available on UI
Example Request
To process source temperatures [0,0.5,0.2,0,1.5,0] with thermometer with freezing temp of 0 and boiling temperature of 100.
Notifications need not be sent with threshold of +-0.5 for both. Payload would look like below

[source,json,subs="+attributes"]
----
{
  "repeatedNotification": false,
  "srcTemps": [
    0,
    0.5,
    0.2,
    0,
    1.5,
    0
  ],
  "thermometerReq": {
    "boilTemperatureSpec": {
      "maxThreshHold": 0.5,
      "minThreshHold": 0.5,
      "temp": 0
    },
    "freezeTemperatureSpec": {
      "maxThreshHold": 0.5,
      "minThreshHold": 0.5,
      "temp": 0
    }
  }
}